"""initial schema

Revision ID: ec63442fcb62
Revises: 
Create Date: 2026-05-27 23:30:03.495614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec63442fcb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy_slug', sa.String(length=120), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('equity_curve_path', sa.String(length=1000), nullable=True),
    sa.Column('drawdown_curve_path', sa.String(length=1000), nullable=True),
    sa.Column('trades_path', sa.String(length=1000), nullable=True),
    sa.Column('summary_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_run_strategy_slug'), ['strategy_slug'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('ranking_date', sa.Date(), nullable=True),
    sa.Column('ranking_source', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('investor_relations_url', sa.String(length=500), nullable=True),
    sa.Column('sec_cik', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('one_line_thesis', sa.String(length=500), nullable=True),
    sa.Column('revenue_segments', sa.JSON(), nullable=True),
    sa.Column('geographic_exposure', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('macro_exposures', sa.JSON(), nullable=True),
    sa.Column('risk_tags', sa.JSON(), nullable=True),
    sa.Column('value_chain_position', sa.Text(), nullable=True),
    sa.Column('moat', sa.Text(), nullable=True),
    sa.Column('management_capital_allocation', sa.Text(), nullable=True),
    sa.Column('unit_economics', sa.Text(), nullable=True),
    sa.Column('growth_drivers', sa.JSON(), nullable=True),
    sa.Column('valuation_notes', sa.Text(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_market_cap_rank'), ['market_cap_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_ticker'), ['ticker'], unique=True)

    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('core_principles', sa.JSON(), nullable=True),
    sa.Column('favorite_setups', sa.JSON(), nullable=True),
    sa.Column('risk_lessons', sa.JSON(), nullable=True),
    sa.Column('mistakes_drawdowns', sa.JSON(), nullable=True),
    sa.Column('representative_investments', sa.JSON(), nullable=True),
    sa.Column('quotes', sa.JSON(), nullable=True),
    sa.Column('strategy_mapping', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('macro_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('transmission_channels', sa.JSON(), nullable=True),
    sa.Column('affected_sectors', sa.JSON(), nullable=True),
    sa.Column('affected_companies', sa.JSON(), nullable=True),
    sa.Column('scenarios', sa.JSON(), nullable=True),
    sa.Column('historical_analogs', sa.JSON(), nullable=True),
    sa.Column('watch_indicators', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('price_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    with op.batch_alter_table('price_bar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_bar_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_bar_symbol'), ['symbol'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('entry_logic', sa.Text(), nullable=True),
    sa.Column('exit_logic', sa.Text(), nullable=True),
    sa.Column('position_sizing', sa.Text(), nullable=True),
    sa.Column('risk_controls', sa.JSON(), nullable=True),
    sa.Column('required_data', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('failure_regimes', sa.JSON(), nullable=True),
    sa.Column('variations_to_test', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('key_beneficiaries', sa.JSON(), nullable=True),
    sa.Column('key_losers', sa.JSON(), nullable=True),
    sa.Column('metrics_to_monitor', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('backtest_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_metric_run_id'), ['run_id'], unique=False)

    op.create_table('company_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=40), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('local_path_raw', sa.String(length=1000), nullable=True),
    sa.Column('local_path_text', sa.String(length=1000), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_for_rag', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_document_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_filing_date'), ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_document_ticker'), ['ticker'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('theme_slug', sa.String(length=120), nullable=True),
    sa.Column('strategy_slug', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_strategy_slug'), ['strategy_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_theme_slug'), ['theme_slug'], unique=False)

    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['company_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunk_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunk_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunk_company_id'))

    op.drop_table('document_chunk')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_theme_slug'))
        batch_op.drop_index(batch_op.f('ix_note_strategy_slug'))
        batch_op.drop_index(batch_op.f('ix_note_company_id'))

    op.drop_table('note')
    with op.batch_alter_table('company_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_document_ticker'))
        batch_op.drop_index(batch_op.f('ix_company_document_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_company_document_filing_date'))
        batch_op.drop_index(batch_op.f('ix_company_document_document_type'))
        batch_op.drop_index(batch_op.f('ix_company_document_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_document_checksum'))

    op.drop_table('company_document')
    with op.batch_alter_table('backtest_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_metric_run_id'))

    op.drop_table('backtest_metric')
    op.drop_table('theme')
    op.drop_table('strategy')
    op.drop_table('source')
    with op.batch_alter_table('price_bar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_bar_symbol'))
        batch_op.drop_index(batch_op.f('ix_price_bar_date'))

    op.drop_table('price_bar')
    op.drop_table('macro_event')
    op.drop_table('investor')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_ticker'))
        batch_op.drop_index(batch_op.f('ix_company_sector'))
        batch_op.drop_index(batch_op.f('ix_company_market_cap_rank'))
        batch_op.drop_index(batch_op.f('ix_company_industry'))
        batch_op.drop_index(batch_op.f('ix_company_country'))

    op.drop_table('company')
    with op.batch_alter_table('backtest_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_run_strategy_slug'))
        batch_op.drop_index(batch_op.f('ix_backtest_run_status'))

    op.drop_table('backtest_run')
    # ### end Alembic commands ###
